In [18]:
import pandas as pd
import pylab as pl
import numpy as np
import scipy.optimize as opt
from sklearn import preprocessing
from sklearn.metrics import f1_score,accuracy_score
%matplotlib inline 
import matplotlib.pyplot as plt

In [19]:
data=pd.read_csv('ChurnData.csv')
data.head()

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   

   longmon  ...  pager  internet  callwait  confer  ebill  loglong  logtoll  \
0     4.40  ...    1.0       0.0       1.0     1.0    0.0    1.482    3.033   
1     9.45  ...    0.0       0.0       0.0     0.0    0.0    2.246    3.240   
2     6.30  ...    0.0       0.0       0.0     1.0    0.0    1.841    3.240   
3     6.05  ...    1.0       1.0       1.0     1.0    1.0    1.800    3.807   
4     7.10  ...    0.0       0.0       1.0     1.0    0.0    1.960    3.091   

   lninc  custcat  churn  
0  4.913      4.0    1.0  
1  3.497      1.0    1.0  
2  3.401      3.0    0.0  
3  4.331      4.0    0.0  
4  4.382      3.0    0.0  

[5 rows x 28 columns]

In [20]:
data = data[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip',   'callcard', 'wireless','churn']]
data['churn'] = data['churn'].astype('int')
data.head()

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   

   churn  
0      1  
1      1  
2      0  
3      0  
4      0

In [21]:
X = np.asarray(data[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip']])
X[0:5]
y = np.asarray(data['churn'])
y [0:5]

array([1, 1, 0, 0, 0])

In [22]:
from sklearn.preprocessing import MinMaxScaler

X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

array([[-1.13518441, -0.62595491, -0.4588971 ,  0.4751423 ,  1.6961288 ,
        -0.58477841, -0.85972695],
       [-0.11604313, -0.62595491,  0.03454064, -0.32886061, -0.6433592 ,
        -1.14437497, -0.85972695],
       [-0.57928917, -0.85594447, -0.261522  , -0.35227817, -1.42318853,
        -0.92053635, -0.85972695],
       [ 0.11557989, -0.47262854, -0.65627219,  0.00679109, -0.6433592 ,
        -0.02518185,  1.16316   ],
       [-1.32048283, -0.47262854,  0.23191574,  0.03801451, -0.6433592 ,
         0.53441472, -0.85972695]])

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (160, 7) (160,)
Test set: (40, 7) (40,)


In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
model = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)


In [25]:
y_pred = model.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0])

In [26]:
y_train_pred = model.predict(X_train)
prob_test=pd.DataFrame(model.predict_proba(X_test))
prob_train=pd.DataFrame(model.predict_proba(X_train))
test_f1_score = f1_score(y_test, y_pred)
train_f1_score = f1_score(y_train, y_train_pred)
train_accuracy=accuracy_score(y_train, y_train_pred)
test_accuracy=accuracy_score(y_test, y_pred)
test_cm = confusion_matrix(y_test, y_pred)
train_cm = confusion_matrix(y_train, y_train_pred)
print('test_accuracy:',test_accuracy)
print('train_accuracy:',train_accuracy)
print('test_f1_score:',test_f1_score)
print('train_f1_score:',train_f1_score)


test_accuracy: 0.75
train_accuracy: 0.7625
test_f1_score: 0.5454545454545455
train_f1_score: 0.5957446808510639


In [27]:
train_cm
test_cm

array([[24,  1],
       [ 9,  6]], dtype=int64)

In [28]:
from sklearn.svm import SVC
svc_model=SVC(gamma='auto',probability=True)

svc_model.fit(X_train,y_train)
y_pred=model.predict(X_test)
y_pred = model.predict(X_test)
y_train_pred = model.predict(X_train)
prob_test=pd.DataFrame(model.predict_proba(X_test))
prob_train=pd.DataFrame(model.predict_proba(X_train))
test_f1_score = f1_score(y_test, y_pred)
train_f1_score = f1_score(y_train, y_train_pred)
train_accuracy=accuracy_score(y_train, y_train_pred)
test_accuracy=accuracy_score(y_test, y_pred)
test_cm = confusion_matrix(y_test, y_pred)
train_cm = confusion_matrix(y_train, y_train_pred)


In [29]:
print('test_accuracy:',test_accuracy)
print('train_accuracy:',train_accuracy)
print('test_f1_score:',test_f1_score)
print('train_f1_score:',train_f1_score)

test_accuracy: 0.75
train_accuracy: 0.7625
test_f1_score: 0.5454545454545455
train_f1_score: 0.5957446808510639


In [30]:
train_cm
test_cm

array([[24,  1],
       [ 9,  6]], dtype=int64)

In [31]:
from sklearn.tree import DecisionTreeClassifier
decision_tree_model=DecisionTreeClassifier()

In [32]:
decision_tree_model.fit(X_train,y_train)
y_pred=decision_tree_model.predict(X_test)
prob_test=pd.DataFrame(decision_tree_model.predict_proba(X_test))
prob_train=pd.DataFrame(decision_tree_model.predict_proba(X_train))
test_f1_score = f1_score(y_test, y_pred)
train_f1_score = f1_score(y_train, y_train_pred)
train_accuracy=accuracy_score(y_train, y_train_pred)
test_accuracy=accuracy_score(y_test, y_pred)
test_cm = confusion_matrix(y_test, y_pred)
train_cm = confusion_matrix(y_train, y_train_pred)
print('test_accuracy:',test_accuracy)
print('train_accuracy:',train_accuracy)
print('test_f1_score:',test_f1_score)
print('train_f1_score:',train_f1_score)

test_accuracy: 0.475
train_accuracy: 0.7625
test_f1_score: 0.22222222222222224
train_f1_score: 0.5957446808510639


In [33]:
train_cm
test_cm

array([[16,  9],
       [12,  3]], dtype=int64)

In [34]:
from sklearn.ensemble import RandomForestClassifier
random_forest_model=RandomForestClassifier(n_estimators=9)
random_forest_model.fit(X_train,y_train)
y_pred=random_forest_model.predict(X_test)
prob_test=pd.DataFrame(random_forest_model.predict_proba(X_test))
prob_train=pd.DataFrame(random_forest_model.predict_proba(X_train))
test_f1_score = f1_score(y_test, y_pred)
train_f1_score = f1_score(y_train, y_train_pred)
train_accuracy=accuracy_score(y_train, y_train_pred)
test_accuracy=accuracy_score(y_test, y_pred)
test_cm = confusion_matrix(y_test, y_pred)
train_cm = confusion_matrix(y_train, y_train_pred)
print('test_accuracy:',test_accuracy)
print('train_accuracy:',train_accuracy)
print('test_f1_score:',test_f1_score)
print('train_f1_score:',train_f1_score)

test_accuracy: 0.675
train_accuracy: 0.7625
test_f1_score: 0.43478260869565216
train_f1_score: 0.5957446808510639


In [35]:
train_cm
test_cm

array([[22,  3],
       [10,  5]], dtype=int64)

In [36]:
from sklearn.neural_network import MLPClassifier
mlp_model=MLPClassifier(max_iter=500,solver='adam')
mlp_model.fit(X_train,y_train)
y_pred=mlp_model.predict(X_test)
prob_test=pd.DataFrame(mlp_model.predict_proba(X_test))
prob_train=pd.DataFrame(mlp_model.predict_proba(X_train))
test_f1_score = f1_score(y_test, y_pred)
train_f1_score = f1_score(y_train, y_train_pred)
train_accuracy=accuracy_score(y_train, y_train_pred)
test_accuracy=accuracy_score(y_test, y_pred)
test_cm = confusion_matrix(y_test, y_pred)
train_cm = confusion_matrix(y_train, y_train_pred)
print('test_accuracy:',test_accuracy)
print('train_accuracy:',train_accuracy)
print('test_f1_score:',test_f1_score)
print('train_f1_score:',train_f1_score)

test_accuracy: 0.65
train_accuracy: 0.7625
test_f1_score: 0.3
train_f1_score: 0.5957446808510639
C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


In [37]:
train_cm
test_cm

array([[23,  2],
       [12,  3]], dtype=int64)

In [38]:
from sklearn.naive_bayes import GaussianNB
gausian= GaussianNB()
gausian.fit(X_train,y_train)
y_pred=gausian.predict(X_test)
prob_test=pd.DataFrame(gausian.predict(X_test))
prob_train=pd.DataFrame(gausian.predict(X_train))
test_f1_score=f1_score(y_test,y_pred)
train_f1_score=f1_score(y_train,y_train_pred)
train_accuracy=accuracy_score(y_train, y_train_pred)
test_accuracy=accuracy_score(y_test, y_pred)
test_cm = confusion_matrix(y_test, y_pred)
train_cm = confusion_matrix(y_train, y_train_pred)
print('test_accuracy:',test_accuracy)
print('train_accuracy:',train_accuracy)
print('test_f1_score:',test_f1_score)
print('train_f1_score:',train_f1_score)
test_cm

test_accuracy: 0.8
train_accuracy: 0.7625
test_f1_score: 0.7647058823529413
train_f1_score: 0.5957446808510639


array([[19,  6],
       [ 2, 13]], dtype=int64)

In [39]:
from sklearn.model_selection import GridSearchCV

In [46]:
params= [{
# 'kernel': ['linear', 'poly', 'rbf', 'sigmoid', 'precomputed'], 
'C': [1,2,3,300,500],
'max_iter': [1000,100000]}]

In [47]:
grid_svc= GridSearchCV(SVC(),params,cv=5,return_train_score=True)
grid_svc.fit(X_train,y_train)

C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\svm\_base.py:255: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn('Solver terminated early (max_iter=%i).'
C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\svm\_base.py:255: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn('Solver terminated early (max_iter=%i).'
C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\svm\_base.py:255: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn('Solver terminated early (max_iter=%i).'
C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\svm\_base.py:255: ConvergenceWarning: Solver terminated 

GridSearchCV(cv=5, estimator=SVC(),
             param_grid=[{'C': [1, 2, 3, 300, 500],
                          'max_iter': [1000, 100000]}],
             return_train_score=True)

In [48]:
y_pred=grid_svc.predict(X_test)
prob_test=pd.DataFrame(grid_svc.predict(X_test))
prob_train=pd.DataFrame(grid_svc.predict(X_train))
test_f1_score=f1_score(y_test,y_pred)
train_f1_score=f1_score(y_train,y_train_pred)
train_accuracy=accuracy_score(y_train, y_train_pred)
test_accuracy=accuracy_score(y_test, y_pred)
test_cm = confusion_matrix(y_test, y_pred)
train_cm = confusion_matrix(y_train, y_train_pred)
print('test_accuracy:',test_accuracy)
print('train_accuracy:',train_accuracy)
print('test_f1_score:',test_f1_score)
print('train_f1_score:',train_f1_score)
test_cm

test_accuracy: 0.725
train_accuracy: 0.7625
test_f1_score: 0.4210526315789474
train_f1_score: 0.5957446808510639


array([[25,  0],
       [11,  4]], dtype=int64)

In [49]:
params={"criterion":['gini','entropy'],"max_depth":range(1,10),"min_samples_split":range(1,15),"min_samples_leaf":range(1,5)}

In [50]:
griddt=GridSearchCV(DecisionTreeClassifier(),params,cv=5,return_train_score=True)

In [51]:
griddt.fit(X_train,y_train)

-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_validation.py", line 598, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\tree\_classes.py", line 903, in fit
    super().fit(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\tree\_classes.py", line 238, in fit
    raise ValueError("min_samples_split must be an integer "
ValueError: min_samples_split must be an integer greater than 1 or a float in (0.0, 1.0]; got the integer 1

  warnings.warn("Estimator fit failed. The score on this train-test"
C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition 

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': range(1, 10),
                         'min_samples_leaf': range(1, 5),
                         'min_samples_split': range(1, 15)},
             return_train_score=True)

In [52]:
y_pred=griddt.predict(X_test)
prob_test=pd.DataFrame(griddt.predict(X_test))
prob_train=pd.DataFrame(griddt.predict(X_train))
test_f1_score=f1_score(y_test,y_pred)
train_f1_score=f1_score(y_train,y_train_pred)
train_accuracy=accuracy_score(y_train, y_train_pred)
test_accuracy=accuracy_score(y_test, y_pred)
test_cm = confusion_matrix(y_test, y_pred)
train_cm = confusion_matrix(y_train, y_train_pred)
print('test_accuracy:',test_accuracy)
print('train_accuracy:',train_accuracy)
print('test_f1_score:',test_f1_score)
print('train_f1_score:',train_f1_score)
test_cm

test_accuracy: 0.7
train_accuracy: 0.7625
test_f1_score: 0.4545454545454545
train_f1_score: 0.5957446808510639


array([[23,  2],
       [10,  5]], dtype=int64)

In [57]:
params = {"penalty":["l1","l2"]}

In [59]:
gridl=GridSearchCV(LogisticRegression(),params,cv=5,return_train_score=True)
gridl.fit(X_train,y_train)

C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_validation.py", line 598, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py", line 1306, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py", line 443, in _check_solver
    raise ValueError("Solver %s supports only 'l2' or 'none' penalties, "
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.

  warnings.warn("Estim

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'penalty': ['l1', 'l2']}, return_train_score=True)

In [60]:
y_pred=gridl.predict(X_test)
prob_test=pd.DataFrame(gridl.predict(X_test))
prob_train=pd.DataFrame(gridl.predict(X_train))
test_f1_score=f1_score(y_test,y_pred)
train_f1_score=f1_score(y_train,y_train_pred)
train_accuracy=accuracy_score(y_train, y_train_pred)
test_accuracy=accuracy_score(y_test, y_pred)
test_cm = confusion_matrix(y_test, y_pred)
train_cm = confusion_matrix(y_train, y_train_pred)
print('test_accuracy:',test_accuracy)
print('train_accuracy:',train_accuracy)
print('test_f1_score:',test_f1_score)
print('train_f1_score:',train_f1_score)
test_cm

test_accuracy: 0.725
train_accuracy: 0.7625
test_f1_score: 0.4210526315789474
train_f1_score: 0.5957446808510639


array([[25,  0],
       [11,  4]], dtype=int64)